version: '3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  web: &rails
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file: .env

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - 'redis:/data'

  sidekiq:
    restart: unless-stopped
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -C config/sidekiq-main.yml
    volumes:
      - '.:/app'

volumes:
  db:
  redis:
  bundle:
