FROM ruby:2.4.10

LABEL maintainer="Kakada Chheang <kakada@instedd.org>"

# Install dependencies
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential \
  default-mysql-client nodejs && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY Gemfile /app/
COPY Gemfile.lock /app/
WORKDIR /app

RUN bundle install

# Install the application
COPY . /app
